
    llm:
    api_key: F7m9CCaa1mVkSqFFgjltjFJqquZE77GRS60ZrW7ja9kjJsfIwt84JQQJ99BIACHrzpqXJ3w3AAAAACOGCE09
    type: azure_openai_chat
    model: gpt-4o
    api_base: https://rohan-mfs2dn0d-northcentralus.cognitiveservices.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
    api_version: 2024-12-01-preview
    deployment_name: gpt-4
    tokens_per_minute: 150000
    requests_per_minute: 1000

    embeddings:
    llm:
        api_key: F7m9CCaa1mVkSqFFgjltjFJqquZE77GRS60ZrW7ja9kjJsfIwt84JQQJ99BIACHrzpqXJ3w3AAAAACOGCE09
        type: azure_openai_embedding
        model: text-embedding-3-large
        api_base: https://rohan-mfs2dn0d-northcentralus.cognitiveservices.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2025-01-01-preview
        api_version: 2024-12-01-preview
        deployment_name: text-embedding-3-large

    input:
    type: file
    base_dir: "./input"
    file_pattern: ".*\.txt$"

    storage:
    type: file
    base_dir: "./output"

    chunk:
    size: 300
    overlap: 100

    entity_extraction:
    entity_types: [organization,person,geo,event]

    local_search:
    top_k_mapped_entities: 10
    max_tokens: 16384
    